import Head from 'next/head'
import stylesheet from '../styles/nextQuestionCard.module.css'
import Header from '@/components/header'
import { Card, CardContent } from '@mui/material'

export default function NextQuestion() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={stylesheet.page_body}>
                <Header></Header>
                <div className={stylesheet.cardBx}>
                    <Card className={stylesheet.card}>
                        <CardContent>
                            <h1>Go to next task?</h1>
                            <p>Some questions have not been answered. Click
                                Go back to complete the questions or Next to proceed.</p>
                            <div className={stylesheet.btn__bx}>
                                <button className={stylesheet.trans__Btn}>Go Back</button>
                                <button className={stylesheet.take__quizBtn}>Next</button>
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </div>
        </>
    )
}
