import Head from 'next/head'
import stylesheet from '../styles/quizInfo.module.css'
import Header from '@/components/header'
import { Card, CardContent } from '@mui/material'
import ReadingQuestion from '@/components/readingQuestion'

const options = ['Option 1', 'Option 2', 'Option 3', 'Option 4'];


export default function QuizInfo() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={stylesheet.page_body}>
        <Header></Header>
        {/* <Card>
            <CardContent className={stylesheet.card__content}>
                <h1>Welcome, you are about to start the 15-minute Quick English Check</h1>
                <div>
                    <div>
                        <img src='../assets/readingicon.svg' />
                        <p>Reading</p>
                        <p>7.5 mins</p>
                    </div>
                </div>
            </CardContent>
        </Card> */}
        <ReadingQuestion question="Select an option:" options={options} />
      </div>
    </>
  )
}
