import Head from 'next/head'
import stylesheet from '../styles/quizForm.module.css'
import Header from '@/components/header'
import { Card, CardContent, TextField } from '@mui/material'

export default function NextQuestion() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={stylesheet.page_body}>
                <Header></Header>
                <div className={stylesheet.cardBx}>
                    <Card className={stylesheet.card}>
                        <CardContent>
                            <h1>You're almost there…</h1>
                            <p>Before viewing your test score, please tell us more about yourself. This information will only be used for academic research purposes on language learning.</p>
                            <TextField className={stylesheet.text__field} id="outlined-basic" label="First name(s)" variant="outlined" />
                            <TextField className={stylesheet.text__field} id="outlined-basic" label="Last name(s)" variant="outlined" />
                            <TextField className={stylesheet.text__field} id="outlined-basic" label="Email" variant="outlined" />
                            <TextField className={stylesheet.text__field} id="outlined-basic" label="Year of Birth" variant="outlined" />
                            <TextField className={stylesheet.text__field} id="outlined-basic" label="Country" variant="outlined" />
                            <TextField className={stylesheet.text__field} id="outlined-basic" label="City" variant="outlined" />
                            <TextField className={stylesheet.text__field} id="outlined-basic" label="Gender" variant="outlined" />
                            <TextField className={stylesheet.text__field} id="outlined-basic" label="Mobile Phone" variant="outlined" />
                            <TextField className={stylesheet.text__field} id="outlined-basic" label="Prefered Learning Method" variant="outlined" />
                            <div className={stylesheet.btn__bx}>
                                <button className={stylesheet.trans__Btn}>View Results</button>
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </div>
        </>
    )
}
